version: '3.1'
services:
    mysql:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=Welcome123$$
            - MYSQL_DATABASE=shopping
        volumes:
            - ./mysql:/var/lib/mysql
        healthcheck:
            test: "/usr/bin/mysql --user=root --password=Welcome123$ --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 20s
            retries: 10
        
    shop-application: 
        image: shop-application
        restart: on-failure
        ports: 
            - 8080:8080 
        environment:
           WAIT_HOSTS: mysql:3306 
        depends_on:
            - mysql
              
        
          
