version: '2'
services:
    mysql:
        image: mysql:8.0
        ports: 
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=Welcome123$
            - MYSQL_USER=root
        volumes:
            - /var/lib/docker/volumes:/var/lib/mysql
    shop-application: 
        image: shop-application
        restart: on-failure
        ports: 
            - 8080:8080
        depends_on:
            - mysql
        
          
